### ISSUE TITLE
Relation to centrioles-tomo-examples?

### ISSUE THREAD

**Issue by constantinpape** [mobie/centrioles-tomo-datasets#2]
Hey @martinschorb, 
what's the difference to https://github.com/mobie/centriole-tomo-examples?

**Comment by martinschorb** [comment]
We decided to split the publications. One that focuses on the methodology and only includes a subset of the data and another one with all data focusing on the biomedical results and implications.

**Comment by constantinpape** [comment]
Ok, good to know! (And we should eventually clarify this in the README)
I will update this one to the new spec as well then.
